In [1]:
import numpy as np
import pandas as pd

In [2]:
file = './data/data.npy'
data = np.load(file)
data

array([[ 14.08      , -20.24      ,   0.79      , ..., 102.        ,
        125.        ,  12.        ],
       [ 14.018     , -19.76      ,   0.78800005, ..., 198.6       ,
        196.4       ,  12.        ],
       [ 14.104287  , -20.175714  ,   0.81214297, ..., 113.78571   ,
        217.35715   ,  12.        ],
       ...,
       [ 11.103     , -19.651999  ,   3.0400002 , ..., 161.4       ,
        170.2       ,   0.        ],
       [ 10.054997  , -22.01832   ,   2.580727  , ..., 141.72728   ,
        150.54546   ,   5.        ],
       [ 12.059001  , -17.72      ,   0.32500002, ..., 100.8       ,
         41.8       ,   7.        ]], dtype=float32)

In [3]:
data[0]

array([ 14.08, -20.24,   0.79,  87.  , 102.  , 125.  ,  12.  ],
      dtype=float32)

In [4]:
data_df = pd.DataFrame(data)
data_df.head()

0          1         2           3           4           5     6
0  14.080000 -20.240000  0.790000   87.000000  102.000000  125.000000  12.0
1  14.018000 -19.760000  0.788000  196.600006  198.600006  196.399994  12.0
2  14.104287 -20.175714  0.812143   52.285713  113.785713  217.357147  12.0
3  14.050834 -20.093336  0.830000  135.583328  165.333328  208.083328  12.0
4  14.018573 -20.094288  0.824286  152.095245  175.952377  205.000000  12.0

In [22]:
data_df[6].isna().sum()
data_df[6].unique()
# some categories not present in this sample dataset

array([12.,  7.,  1.,  2., 10.,  6.,  4., 11.,  8.,  5.,  9.,  0.],
      dtype=float32)

In [25]:
# coords = data_df[[0,1,2]]
# coords.head()

0          1         2
0  14.080000 -20.240000  0.790000
1  14.018000 -19.760000  0.788000
2  14.104287 -20.175714  0.812143
3  14.050834 -20.093336  0.830000
4  14.018573 -20.094288  0.824286

In [29]:
# pixel_values = data_df[[3, 4, 5]]
# pixel_values.head()

3           4           5
0   87.000000  102.000000  125.000000
1  196.600006  198.600006  196.399994
2   52.285713  113.785713  217.357147
3  135.583328  165.333328  208.083328
4  152.095245  175.952377  205.000000

In [30]:
# # normalize pixel values
# print (f"Max pixel values: {pixel_values[3].max()}, {pixel_values[4].max()}, {pixel_values[5].max()}")
# print (f"Min pixel values: {pixel_values[3].min()}, {pixel_values[4].min()}, {pixel_values[5].min()}")
# pixel_values = pixel_values / 255.0
# print (f"Max pixel values: {pixel_values[3].max()}, {pixel_values[4].max()}, {pixel_values[5].max()}")
# print (f"Min pixel values: {pixel_values[3].min()}, {pixel_values[4].min()}, {pixel_values[5].min()}")

Max pixel values: 255.0, 255.0, 255.0
Min pixel values: 4.714285850524902, 5.0, 0.0
Max pixel values: 1.0, 1.0, 1.0
Min pixel values: 0.01848739549225452, 0.0196078431372549, 0.0


In [33]:
# labels = data_df[6]
# labels.head()

0    12.0
1    12.0
2    12.0
3    12.0
4    12.0
Name: 6, dtype: float32

In [5]:
# Normalize Pixel Values - Z-score

# data_df[[3, 4, 5]] = data_df[[3, 4, 5]] / 255.0
print (f"Max pixel values: {data_df[3].max()}, {data_df[4].max()}, {data_df[5].max()}")
print (f"Min pixel values: {data_df[3].min()}, {data_df[4].min()}, {data_df[5].min()}")

data_df[3] = (data_df[3] - data_df[3].mean()) / data_df[3].std()
data_df[4] = (data_df[4] - data_df[4].mean()) / data_df[4].std()
data_df[5] = (data_df[5] - data_df[5].mean()) / data_df[5].std()

print (f"Max pixel values: {data_df[3].max()}, {data_df[4].max()}, {data_df[5].max()}")
print (f"Min pixel values: {data_df[3].min()}, {data_df[4].min()}, {data_df[5].min()}")

data_df.head()

Max pixel values: 255.0, 255.0, 255.0
Min pixel values: 4.714285850524902, 5.0, 0.0
Max pixel values: 2.571589226074063, 2.5669072529309367, 2.502662025147529
Min pixel values: -2.448472632085461, -2.3445418733713064, -2.165490748887357


0          1         2         3         4         5     6
0  14.080000 -20.240000  0.790000 -0.798041 -0.438900  0.122819  12.0
1  14.018000 -19.760000  0.788000  1.400242  1.458884  1.429902  12.0
2  14.104287 -20.175714  0.812143 -1.494317 -0.207360  1.813554  12.0
3  14.050834 -20.093336  0.830000  0.176410  0.805334  1.643783  12.0
4  14.018573 -20.094288  0.824286  0.507595  1.013954  1.587338  12.0

In [45]:
temp = data_df[[0,1,2]].to_numpy()
temp.shape

from collections import defaultdict
unique_locations = defaultdict(int)

for a_row in temp:
    t = [f"{a_row[0]:.3f}", f"{a_row[1]:.3f}", f"{a_row[2]:.3f}"]
#     unique_locations[str(a_row.tolist())] += 1
    unique_locations[str(t)] += 1
    
# a = unique_locations.values()
print (temp.shape)
print (len(unique_locations))
unique_locations

(111620, 3)
111620


defaultdict(int,
            {"['14.080', '-20.240', '0.790']": 1,
             "['14.018', '-19.760', '0.788']": 1,
             "['14.104', '-20.176', '0.812']": 1,
             "['14.051', '-20.093', '0.830']": 1,
             "['14.019', '-20.094', '0.824']": 1,
             "['13.975', '-20.098', '0.820']": 1,
             "['14.016', '-20.016', '0.820']": 1,
             "['14.055', '-20.017', '0.825']": 1,
             "['14.099', '-20.014', '0.824']": 1,
             "['14.088', '-20.092', '0.830']": 1,
             "['13.966', '-20.226', '0.788']": 1,
             "['13.977', '-20.209', '0.804']": 1,
             "['14.057', '-19.760', '0.787']": 1,
             "['14.070', '-19.800', '0.790']": 1,
             "['13.800', '-20.095', '0.790']": 1,
             "['13.920', '-19.880', '0.790']": 1,
             "['13.886', '-19.924', '0.790']": 1,
             "['13.812', '-20.016', '0.790']": 1,
             "['13.898', '-19.933', '0.800']": 1,
             "['13.830', '-20.025

In [35]:
# # Sanity Check
# print (f"Coords: {coords.shape}")
# print (f"Pixel Values: {pixel_values.shape}")
# print (f"Labels: {labels.shape}")

Coords: (111620, 3)
Pixel Values: (111620, 3)
Labels: (111620,)


In [46]:
data_df.to_pickle('data/data.pkl')